package com.linkedkeeper.tcp.connector.tcp.codec;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBuf.proto

public final class MessageBuf {
  private MessageBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JMTransferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JMTransfer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required string version = 1;</code>
     */
    String getVersion();
    /**
     * <code>required string version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>required string deviceId = 2;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required string deviceId = 2;</code>
     */
    String getDeviceId();
    /**
     * <code>required string deviceId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>required uint32 cmd = 3;</code>
     */
    boolean hasCmd();
    /**
     * <code>required uint32 cmd = 3;</code>
     */
    int getCmd();

    /**
     * <code>required uint64 seq = 4;</code>
     */
    boolean hasSeq();
    /**
     * <code>required uint64 seq = 4;</code>
     */
    long getSeq();

    /**
     * <code>required uint32 format = 5;</code>
     */
    boolean hasFormat();
    /**
     * <code>required uint32 format = 5;</code>
     */
    int getFormat();

    /**
     * <code>required uint32 flag = 6;</code>
     */
    boolean hasFlag();
    /**
     * <code>required uint32 flag = 6;</code>
     */
    int getFlag();

    /**
     * <code>required string platform = 7;</code>
     */
    boolean hasPlatform();
    /**
     * <code>required string platform = 7;</code>
     */
    String getPlatform();
    /**
     * <code>required string platform = 7;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <code>required string platformVersion = 8;</code>
     */
    boolean hasPlatformVersion();
    /**
     * <code>required string platformVersion = 8;</code>
     */
    String getPlatformVersion();
    /**
     * <code>required string platformVersion = 8;</code>
     */
    com.google.protobuf.ByteString
        getPlatformVersionBytes();

    /**
     * <code>required string token = 9;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 9;</code>
     */
    String getToken();
    /**
     * <code>required string token = 9;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>required string appKey = 10;</code>
     */
    boolean hasAppKey();
    /**
     * <code>required string appKey = 10;</code>
     */
    String getAppKey();
    /**
     * <code>required string appKey = 10;</code>
     */
    com.google.protobuf.ByteString
        getAppKeyBytes();

    /**
     * <code>required string timeStamp = 11;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required string timeStamp = 11;</code>
     */
    String getTimeStamp();
    /**
     * <code>required string timeStamp = 11;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>required string sign = 12;</code>
     */
    boolean hasSign();
    /**
     * <code>required string sign = 12;</code>
     */
    String getSign();
    /**
     * <code>required string sign = 12;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();

    /**
     * <code>optional bytes body = 20;</code>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 20;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code JMTransfer}
   */
  public static final class JMTransfer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:JMTransfer)
      JMTransferOrBuilder {
    // Use JMTransfer.newBuilder() to construct.
    private JMTransfer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JMTransfer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JMTransfer defaultInstance;
    public static JMTransfer getDefaultInstance() {
      return defaultInstance;
    }

    public JMTransfer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JMTransfer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              version_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              deviceId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cmd_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              seq_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              format_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              flag_ = input.readUInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              platform_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              platformVersion_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              token_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              appKey_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              timeStamp_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              sign_ = bs;
              break;
            }
            case 162: {
              bitField0_ |= 0x00001000;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageBuf.internal_static_JMTransfer_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageBuf.internal_static_JMTransfer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JMTransfer.class, Builder.class);
    }

    public static com.google.protobuf.Parser<JMTransfer> PARSER =
        new com.google.protobuf.AbstractParser<JMTransfer>() {
      public JMTransfer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JMTransfer(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<JMTransfer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private Object version_;
    /**
     * <code>required string version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string version = 1;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEID_FIELD_NUMBER = 2;
    private Object deviceId_;
    /**
     * <code>required string deviceId = 2;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string deviceId = 2;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 3;
    private int cmd_;
    /**
     * <code>required uint32 cmd = 3;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 cmd = 3;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int SEQ_FIELD_NUMBER = 4;
    private long seq_;
    /**
     * <code>required uint64 seq = 4;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint64 seq = 4;</code>
     */
    public long getSeq() {
      return seq_;
    }

    public static final int FORMAT_FIELD_NUMBER = 5;
    private int format_;
    /**
     * <code>required uint32 format = 5;</code>
     */
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 format = 5;</code>
     */
    public int getFormat() {
      return format_;
    }

    public static final int FLAG_FIELD_NUMBER = 6;
    private int flag_;
    /**
     * <code>required uint32 flag = 6;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint32 flag = 6;</code>
     */
    public int getFlag() {
      return flag_;
    }

    public static final int PLATFORM_FIELD_NUMBER = 7;
    private Object platform_;
    /**
     * <code>required string platform = 7;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string platform = 7;</code>
     */
    public String getPlatform() {
      Object ref = platform_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          platform_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string platform = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORMVERSION_FIELD_NUMBER = 8;
    private Object platformVersion_;
    /**
     * <code>required string platformVersion = 8;</code>
     */
    public boolean hasPlatformVersion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string platformVersion = 8;</code>
     */
    public String getPlatformVersion() {
      Object ref = platformVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          platformVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string platformVersion = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformVersionBytes() {
      Object ref = platformVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        platformVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 9;
    private Object token_;
    /**
     * <code>required string token = 9;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string token = 9;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPKEY_FIELD_NUMBER = 10;
    private Object appKey_;
    /**
     * <code>required string appKey = 10;</code>
     */
    public boolean hasAppKey() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string appKey = 10;</code>
     */
    public String getAppKey() {
      Object ref = appKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appKey = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAppKeyBytes() {
      Object ref = appKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 11;
    private Object timeStamp_;
    /**
     * <code>required string timeStamp = 11;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string timeStamp = 11;</code>
     */
    public String getTimeStamp() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeStamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timeStamp = 11;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGN_FIELD_NUMBER = 12;
    private Object sign_;
    /**
     * <code>required string sign = 12;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required string sign = 12;</code>
     */
    public String getSign() {
      Object ref = sign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sign = 12;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 20;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bytes body = 20;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private void initFields() {
      version_ = "";
      deviceId_ = "";
      cmd_ = 0;
      seq_ = 0L;
      format_ = 0;
      flag_ = 0;
      platform_ = "";
      platformVersion_ = "";
      token_ = "";
      appKey_ = "";
      timeStamp_ = "";
      sign_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFormat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlatform()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlatformVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, seq_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, format_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, flag_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getPlatformBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getPlatformVersionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getTokenBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getAppKeyBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getTimeStampBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getSignBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(20, body_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, cmd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, seq_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, format_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, flag_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getPlatformBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getPlatformVersionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getTokenBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getAppKeyBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getTimeStampBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getSignBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static JMTransfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JMTransfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JMTransfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JMTransfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JMTransfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JMTransfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static JMTransfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static JMTransfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static JMTransfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JMTransfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JMTransfer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JMTransfer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JMTransfer)
        JMTransferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageBuf.internal_static_JMTransfer_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageBuf.internal_static_JMTransfer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JMTransfer.class, Builder.class);
      }

      // Construct using MessageBuf.JMTransfer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        format_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        platform_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        platformVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        appKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        timeStamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageBuf.internal_static_JMTransfer_descriptor;
      }

      public JMTransfer getDefaultInstanceForType() {
        return JMTransfer.getDefaultInstance();
      }

      public JMTransfer build() {
        JMTransfer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public JMTransfer buildPartial() {
        JMTransfer result = new JMTransfer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.seq_ = seq_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.format_ = format_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.platformVersion_ = platformVersion_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.appKey_ = appKey_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.sign_ = sign_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JMTransfer) {
          return mergeFrom((JMTransfer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JMTransfer other) {
        if (other == JMTransfer.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          bitField0_ |= 0x00000001;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000002;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        if (other.hasFormat()) {
          setFormat(other.getFormat());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasPlatform()) {
          bitField0_ |= 0x00000040;
          platform_ = other.platform_;
          onChanged();
        }
        if (other.hasPlatformVersion()) {
          bitField0_ |= 0x00000080;
          platformVersion_ = other.platformVersion_;
          onChanged();
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000100;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasAppKey()) {
          bitField0_ |= 0x00000200;
          appKey_ = other.appKey_;
          onChanged();
        }
        if (other.hasTimeStamp()) {
          bitField0_ |= 0x00000400;
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (other.hasSign()) {
          bitField0_ |= 0x00000800;
          sign_ = other.sign_;
          onChanged();
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasCmd()) {
          
          return false;
        }
        if (!hasSeq()) {
          
          return false;
        }
        if (!hasFormat()) {
          
          return false;
        }
        if (!hasFlag()) {
          
          return false;
        }
        if (!hasPlatform()) {
          
          return false;
        }
        if (!hasPlatformVersion()) {
          
          return false;
        }
        if (!hasToken()) {
          
          return false;
        }
        if (!hasAppKey()) {
          
          return false;
        }
        if (!hasTimeStamp()) {
          
          return false;
        }
        if (!hasSign()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JMTransfer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JMTransfer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object version_ = "";
      /**
       * <code>required string version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string version = 1;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string version = 1;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <code>required string deviceId = 2;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string deviceId = 2;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceId = 2;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceId = 2;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceId = 2;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }

      private int cmd_ ;
      /**
       * <code>required uint32 cmd = 3;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 cmd = 3;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>required uint32 cmd = 3;</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000004;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 cmd = 3;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = 0;
        onChanged();
        return this;
      }

      private long seq_ ;
      /**
       * <code>required uint64 seq = 4;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint64 seq = 4;</code>
       */
      public long getSeq() {
        return seq_;
      }
      /**
       * <code>required uint64 seq = 4;</code>
       */
      public Builder setSeq(long value) {
        bitField0_ |= 0x00000008;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 seq = 4;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000008);
        seq_ = 0L;
        onChanged();
        return this;
      }

      private int format_ ;
      /**
       * <code>required uint32 format = 5;</code>
       */
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 format = 5;</code>
       */
      public int getFormat() {
        return format_;
      }
      /**
       * <code>required uint32 format = 5;</code>
       */
      public Builder setFormat(int value) {
        bitField0_ |= 0x00000010;
        format_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 format = 5;</code>
       */
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        format_ = 0;
        onChanged();
        return this;
      }

      private int flag_ ;
      /**
       * <code>required uint32 flag = 6;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint32 flag = 6;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <code>required uint32 flag = 6;</code>
       */
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000020;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 flag = 6;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000020);
        flag_ = 0;
        onChanged();
        return this;
      }

      private Object platform_ = "";
      /**
       * <code>required string platform = 7;</code>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string platform = 7;</code>
       */
      public String getPlatform() {
        Object ref = platform_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            platform_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string platform = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string platform = 7;</code>
       */
      public Builder setPlatform(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string platform = 7;</code>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000040);
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>required string platform = 7;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        platform_ = value;
        onChanged();
        return this;
      }

      private Object platformVersion_ = "";
      /**
       * <code>required string platformVersion = 8;</code>
       */
      public boolean hasPlatformVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string platformVersion = 8;</code>
       */
      public String getPlatformVersion() {
        Object ref = platformVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            platformVersion_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string platformVersion = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformVersionBytes() {
        Object ref = platformVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          platformVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string platformVersion = 8;</code>
       */
      public Builder setPlatformVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        platformVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string platformVersion = 8;</code>
       */
      public Builder clearPlatformVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        platformVersion_ = getDefaultInstance().getPlatformVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string platformVersion = 8;</code>
       */
      public Builder setPlatformVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        platformVersion_ = value;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <code>required string token = 9;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string token = 9;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string token = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 9;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 9;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000100);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 9;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        token_ = value;
        onChanged();
        return this;
      }

      private Object appKey_ = "";
      /**
       * <code>required string appKey = 10;</code>
       */
      public boolean hasAppKey() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string appKey = 10;</code>
       */
      public String getAppKey() {
        Object ref = appKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appKey_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string appKey = 10;</code>
       */
      public com.google.protobuf.ByteString
          getAppKeyBytes() {
        Object ref = appKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appKey = 10;</code>
       */
      public Builder setAppKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        appKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appKey = 10;</code>
       */
      public Builder clearAppKey() {
        bitField0_ = (bitField0_ & ~0x00000200);
        appKey_ = getDefaultInstance().getAppKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string appKey = 10;</code>
       */
      public Builder setAppKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        appKey_ = value;
        onChanged();
        return this;
      }

      private Object timeStamp_ = "";
      /**
       * <code>required string timeStamp = 11;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string timeStamp = 11;</code>
       */
      public String getTimeStamp() {
        Object ref = timeStamp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timeStamp_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string timeStamp = 11;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timeStamp = 11;</code>
       */
      public Builder setTimeStamp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timeStamp = 11;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timeStamp = 11;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private Object sign_ = "";
      /**
       * <code>required string sign = 12;</code>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required string sign = 12;</code>
       */
      public String getSign() {
        Object ref = sign_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sign_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sign = 12;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sign = 12;</code>
       */
      public Builder setSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 12;</code>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 12;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        sign_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 20;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bytes body = 20;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 20;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 20;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00001000);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:JMTransfer)
    }

    static {
      defaultInstance = new JMTransfer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:JMTransfer)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JMTransfer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JMTransfer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020MessageBuf.proto\"\340\001\n\nJMTransfer\022\017\n\007ver" +
      "sion\030\001 \002(\t\022\020\n\010deviceId\030\002 \002(\t\022\013\n\003cmd\030\003 \002(" +
      "\r\022\013\n\003seq\030\004 \002(\004\022\016\n\006format\030\005 \002(\r\022\014\n\004flag\030\006" +
      " \002(\r\022\020\n\010platform\030\007 \002(\t\022\027\n\017platformVersio" +
      "n\030\010 \002(\t\022\r\n\005token\030\t \002(\t\022\016\n\006appKey\030\n \002(\t\022\021" +
      "\n\ttimeStamp\030\013 \002(\t\022\014\n\004sign\030\014 \002(\t\022\014\n\004body\030" +
      "\024 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JMTransfer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JMTransfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_JMTransfer_descriptor,
        new String[] { "Version", "DeviceId", "Cmd", "Seq", "Format", "Flag", "Platform", "PlatformVersion", "Token", "AppKey", "TimeStamp", "Sign", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
